version: '3.6'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: niraj
      POSTGRES_PASSWORD: 0bb380f1af3272233e87dac79a75d452
      POSTGRES_DB: bulk_email_processor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bulk_email_processor_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: khadka.niraj11111@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 646f29bafc99269a3a2d1d4b1caf9230
    depends_on:
      - db 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bulk_email_processor_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: niraj
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - bulk_email_processor_network   

  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USERNAME: niraj
      DB_PASSWORD: 0bb380f1af3272233e87dac79a75d452
      DB_DATABASE: bulk_email_processor
      DB_PORT: 5432
      RABBITMQ_USER: niraj
      RABBITMQ_PASS: password
      RABBITMQ_HOST: rabbitmq
    volumes:
      - ./backend:/var/www/bulk_email_processor/backend/
    depends_on:
      - db
      - rabbitmq
      - pgadmin
    networks:
      - bulk_email_processor_network 

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/var/www/bulk_email_processor/frontend
    depends_on:
      - backend
    networks:
      - bulk_email_processor_network
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/bulk_email_processor/frontend/
    depends_on:
      - backend
    networks:
      - bulk_email_processor_network

networks:
  bulk_email_processor_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
