  version: '3.6'

  services:
    backend:
      build:
        context: ./backend
      ports:
        - "8000:8000"
      environment:
        - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
      volumes:
        - ./backend:/var/www/bulk_email_processor/backend/
      networks:
        - bulk_email_processor

    db:
      image: postgres:16
      restart: always
      environment:
        POSTGRES_PASSWORD: 0bb380f1af3272233e87dac79a75d452
        POSTGRES_DB: bulk_email_processor
        POSTGRES_USER: niraj
      ports:
        - "5432:5432"
      networks:
        - bulk_email_processor

    pgadmin:
      image: dpage/pgadmin4
      ports:
        - "5050:80"
      environment:
        - PGADMIN_DEFAULT_EMAIL=khadka.niraj11111@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=646f29bafc99269a3a2d1d4b1caf9230
      networks:
        - bulk_email_processor

    nginx:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend
      networks:
        - bulk_email_processor

  networks:
    bulk_email_processor:
      driver: bridge
